language: node_js
caches:
  directories:
    - ~/.
node_js:
  - '12'
git: 
  depth: 3
script:
  -yarn build
deploy:
  provider: pages
  edge: true
  cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh_pages
  commit-message: "Deploy works"
  on:
    branch: main
